# The URL the site will be built for
base_url = "https://notmatthew.io"

title = "notmatthew.io"
description = "You have not found matthew's homepage"

default_language = "en"

compile_sass = false
build_search_index = false

[markdown]
highlight_code = false

[extra]
keywords = ["put", "your", "pagewide", "keywords", "here"]
author = "Matthew Baltrusitis"
